<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Views\Dashboard\" />
    <Folder Include="Areas\Admin\Views\GymLocations\" />
    <Folder Include="Areas\Admin\Views\WorkoutClasses\" />
    <Folder Include="Areas\Admin\Views\Trainers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymMembershipSystem.Data\GymMembershipSystem.Data.csproj" />
    <ProjectReference Include="..\GymMembershipSystem.Services\GymMembershipSystem.Services.csproj" />
  </ItemGroup>

</Project>
